"""periodic_tasks

Revision ID: 9e31a6aa021a
Revises: 64c2a4bb18e1
Create Date: 2020-12-13 16:23:01.763948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e31a6aa021a'
down_revision = '64c2a4bb18e1'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crontab', sa.JSON(), nullable=False),
    sa.Column('queue', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expire_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('periodic_tasks_pkey')),
    sa.UniqueConstraint('name', name=op.f('periodic_tasks_name_key')),
    schema='collection_builder'
    )
    op.create_index(op.f('idx_collection_builder_periodic_tasks_name'), 'periodic_tasks', ['name'], unique=False, schema='collection_builder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_collection_builder_periodic_tasks_name'), table_name='periodic_tasks', schema='collection_builder')
    op.drop_table('periodic_tasks', schema='collection_builder')
    # ### end Alembic commands ###
